apiVersion: v1
data:
  #dummy base64 encoded passwords:  echo -n 'password123456789'|base64
  MYSQL_PASSWORD: cGFzc3dvcmQxMjM0NTY3ODk=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQxMjM0NTY3ODk=
kind: Secret
metadata:
  name: seafile-secrets
type: Opaque
