kind: Service
apiVersion: v1
metadata:
  name: mysql
  labels:
    service: mysql
    project: seafile
spec:
  ports:
    - name: mysql
      protocol: TCP
      targetPort: mysql
      port: 3306
  selector:
    run: mysql
    project: seafile
