apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    project: seafile
    run: mysql
  name: mysql-seafile
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: mysql-seafile
