apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: seafile
    run: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          value: seafile
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: seafile-secrets
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: seafile-secrets
        - name: MYSQL_DATABASE
          value: seafile
        image: quay.io/neith00/mysql-docker@sha256:57afbcc633ead05c662b335d2643d5f97ec04d056ac31d7f89643bb36a2e5aa5 
        imagePullPolicy: IfNotPresent
        name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-seafile
      restartPolicy: Always
      securityContext:
        runAsUser: 27
      volumes:
      - name: mysql-seafile
        persistentVolumeClaim:
          claimName: mysql-seafile
