apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-seafile
  labels:
    project: seafile
    run: mysql
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /volume1/k8s_share/seafile/mysql
    server: 192.168.1.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
